### ISSUE TITLE
Disable Auto group change?

### ISSUE THREAD

**Issue by infabo** [integer-net/EuropeanTax#2]
https://www.integer-net.com/tax-configuration-eu-for-b2b-and-b2c-stores/

> Solution: Separation of Tax Class and Customer Group
> 
> In order to solve this problem, we decided not to make a change of customer group depending on VAT ID. Instead, the customer tax class is only set when it is needed. So we added an additional field in the customer group settings: a tax class which is to be used in case of a valid VAT ID.

Actually the opposite happens when installing the module:

https://github.com/integer-net/EuropeanTax/blob/master/src/app/code/community/IntegerNet/EuropeanTax/sql/integernet_europeantax_setup/upgrade-0.3.0-0.4.0.php#L8

Any thoughts on this?

**Comment by avstudnitz** [comment]
You are totally right.
