### ISSUE TITLE
how this module work

### ISSUE THREAD

**Issue by sebadiginet** [integer-net/EuropeanTax#3]
I don't know how this module work -
It assign or not assign customer group automaticaly with proper VAT ID ?
After install it looks thats Don't assign customer groups automatically

**Comment by avstudnitz** [comment]
It's described in https://www.integer-net.com/tax-configuration-eu-for-b2b-and-b2c-stores/, among with other modules and settings. Sorry, the link should be in the readme.

**Comment by Schrank** [comment]
Link is in the readme, can be closed.
